package com.snoweegamecorp.CRUD.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
//Entity- set this class as a table
//Table- set a table name
@Entity
@Table(name = "messages")
public class Messages {
	
		//Id- set this field as a IDENTIFIER
		//GeneratedValue- set as autogenerated value
		@Id
		@GeneratedValue(strategy = GenerationType.IDENTITY)
		private long id;
		
		//NotNull- set this to not be null
		//Size- set a min and a max value for the field
		@NotNull
		@Size(min = 5, max = 1000)
		private String title;
		
		@NotNull
		@Size(min = 10, max = 500)
		private String text;
		
		//Temporal- set this as a instance os time
		@Temporal(TemporalType.TIMESTAMP)
		private Date date = new java.sql.Date(System.currentTimeMillis());

		public long getId() {
			return id;
		}

		public void setId(long id) {
			this.id = id;
		}

		public String getTitle() {
			return title;
		}

		public void setTitle(String title) {
			this.title = title;
		}

		public String getText() {
			return text;
		}

		public void setText(String text) {
			this.text = text;
		}

		public Date getDate() {
			return date;
		}

		public void setDate(Date date) {
			this.date = date;
		}
}
